# check if /tmp/{{ domain.domain }}_client_configs.txt exists
# if it does, skip
- name: Check if /tmp/{{ domain.domain }}_client_configs.txt exists
  stat:
    path: "/tmp/{{ domain.domain }}_client_configs.txt"
  register: stat_result

- name: Generate and store configs - {{ domain.domain }}
  include_tasks: subdomain_task.yml
  loop: "{{ domain.subdomains }}"
  loop_control:
    loop_var: subdomain
  when: stat_result.stat.exists == False
