---
# tasks file for nginx_role
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
- name: Generate NGINX configuration for each domain
  template:
    src: templates/domain.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
  loop: "{{ domains }}"
- name: Copy nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx
