---
# handlers file for iptables_role
- name: Restart iptables
  service:
    name: iptables
    state: restarted
  ignore_errors: yes
- name: Restore iptables
  shell: iptables-restore < /etc/iptables/rules.v4
  ignore_errors: yes
